version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: always
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
         mynet:
           ipv4_address: 172.40.0.2

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8888:82
    networks:
         mynet:
           ipv4_address: 172.40.0.3

  # The Database
  database:
    image: mysql:5.7.21
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=secco"
      - "MYSQL_USER=username"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33064:3307"
    networks:
         mynet:
           ipv4_address: 172.40.0.5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'database:mysql'
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: username
      PMA_PASSWORD: secret
    ports:
        - '8989:82'
    networks:
         mynet:
           ipv4_address: 172.40.0.4

  monogodb:
     image: mongo:3.6.4
     environment:
       - "MONGO_DATA_DIR=/data/db"
       - "MONGO_LOG_DIR=/dev/null"
       - "MONGODB_USER=username"
       - "MONGODB_PASS=secret"
     volumes:
       - ./data/db:/data/db
     ports:
         - 27018:27017
     command: mongod --smallfiles --logpath=/dev/null # --quiet
     networks:
              mynet:
                ipv4_address: 172.40.0.7

networks:
 mynet:
   driver: bridge
   ipam:
     config:
     - subnet: 172.40.0.0/24

volumes:
  dbdata:
